spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/amr_pvms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:amr_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:amr_pass123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:dev_local_test_secret_change_this_later}
jwt.expiration=86400000
abdm.client-id=SBXID_053766
abdm.client-secret=863c8977-a5db-47d9-b622-90bac71342fa