spring.datasource.url=jdbc:postgresql://localhost:5432/amr_pvms
spring.datasource.username=amr_admin
spring.datasource.password=amr_pass123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
jwt.secret=amrpvms2026SuperSecretKeyForJWTSigningMustBeLongEnough123456
jwt.expiration=86400000